### ISSUE TITLE
Can't run the plugin

### ISSUE THREAD

**Issue by natarslan** [liammagee/obsidian-topic-linking#1]
Thank you for this plugin. It's a great idea.

I tried the plugin with few pdf files. When I run "Extract markdown from pdfs" I get the following message:

Uncaught (in promise) TypeError: markdownText.replaceAll is not a function
at PDFContentExtractor.processPDF (eval at <anonymous> (app.js:1), <anonymous>:10155:39)
at async PDFContentExtractor.extract (eval at <anonymous> (app.js:1), <anonymous>:10245:7)

**Comment by liammagee** [comment]
Sorry for the late response. Best guess this is an Obsidian versioning issue? Could you send through the version you're running? Failing that, do you mind posting the PDFs you've tested with - I'll see if I can reproduce this error.

**Comment by eleanorkonik** [comment]
I got the same error. 

![image](https://user-images.githubusercontent.com/75856959/158089563-f01162df-5010-440b-9fe0-1ccee9b7204d.png)

Here are the pdfs I was using, happy to send them over if it helps:

![image](https://user-images.githubusercontent.com/75856959/158089629-3ecf7db9-e0ed-44af-8e23-7a063ee8ecea.png)
