### ISSUE TITLE
invalid count value

### ISSUE THREAD

**Issue by eleanorkonik** [liammagee/obsidian-topic-linking#2]
When I tried to run the plugin I got the following error:

![image](https://user-images.githubusercontent.com/75856959/158089563-f01162df-5010-440b-9fe0-1ccee9b7204d.png)

Here are the pdfs I was using, happy to send them over if it helps:

![image](https://user-images.githubusercontent.com/75856959/158089629-3ecf7db9-e0ed-44af-8e23-7a063ee8ecea.png)

**Comment by liammagee** [comment]
Thanks - this should now be fixed.
