### ISSUE TITLE
"Extract Markdown From PDFs" not generating any markdown files, only folder structure

### ISSUE THREAD

**Issue by axb21** [liammagee/obsidian-topic-linking#5]
Obsidian v0.14.10, installer version 0.13.30, plugin version 0.1.5, Ubuntu 21.04.

I've tried this plugin on two different vaults and three different folders of PDFs: one large (1700 files), one medium (180 files), one small (40 files). I've tried with all default settings as well as customized settings.

In almost all cases, when I run the "Extract Markdown From PDFs" command, the plugin correctly reconstructs the folder structure of my PDF folder under Generated/, but creates no markdown files. In one (seemingly anomalous) case, a single markdown file was produced. I ran the plugin on this same vault/folder combination and had it produce 0 markdown files, so I'm unsure why it produced only one in one of my tests.

The plugin is not generating any messages in Obsidian or log files that I can find, so I don't know where to begin diagnosing what could be wrong. Please advise. The functionality looks great and I'd love to be able to use it!

**Comment by liammagee** [comment]
Thanks for filling this. I've been away from this plugin for a few weeks, but returning to it over the next month. Do you mind posting the small folder, if the data is not too sensitive, and I'll see if I can reproduce it?

**Comment by axb21** [comment]
Sorry it's taken me a long time to report back. I've been trying to create a small demo vault for you, but whenever I make a new vault, the "Extract Markdown from PDFs" command works exactly as expected. Previously, I had (in spite of your warnings) tried the plugin on a large vault I use regularly, and that's where I encountered problems. I'm a little reluctant to do that again, and in any case I couldn't share that vault. I'm starting to think the problem might be some conflict among plugins I have instsalled, or maybe something weird with one of my PDF files?

So, I'm not sure what to say! Sorry I couldn't provide a replicable test case.

**Comment by Heischo99** [comment]
I have observed that "Extract Markdown from PDFs" stalls when it encounters a password protected PDF (a PDF that can be displayed, but making changes to it or reading out its content requires entering a password.
Maybe this is the cause for the failures you are seeing?

**Comment by axb21** [comment]
> I have observed that "Extract Markdown from PDFs" stalls when it encounters a password protected PDF (a PDF that can be displayed, but making changes to it or reading out its content requires entering a password. Maybe this is the cause for the failures you are seeing?

Interesting. That's certainly possible. In my case, it looks like the issue might have been peculiar to my vault, not so much the PDF files.

**Comment by liammagee** [comment]
Thanks both, I'll test with password-protected files soon. That might be the same issue for a few people.
